--- #YAML:1.0
name:               Parse-RecDescent
version:            1.966_000
abstract:           Generate Recursive-Descent Parsers
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:      0
    Text::Balanced:  0
    version:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
